volumes:
  gitlab-ce-docker:
    name: gitlab-ce-docker
  gitlab-runner-docker:
    name: gitlab-runner-docker
  staging-docker:
    name: staging-docker
  staging-user:
    name: staging-user

services:
  gitlab-ce-vps:
    image: simple-vps
    container_name: gitlab-ce-vps
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${GITLAB_CE_PORT}:${GITLAB_CE_PORT}
      - ${GITLAB_CE_REGISTRY_PORT}:${GITLAB_CE_REGISTRY_PORT}
    volumes:
      - ./gitlab-ce:/opt/gitlab-ce
      - gitlab-ce-docker:/var/lib/docker
    env_file:
      - .env
  gitlab-runner-vps:
    image: simple-vps
    container_name: gitlab-runner-vps
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./gitlab-runner:/opt/gitlab-runner
      - gitlab-runner-docker:/var/lib/docker
    env_file:
      - .env
  staging-vps:
    image: simple-vps
    container_name: staging-vps
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${STAGING_PORT}:80
      - ${STAGING_SSH_PORT}:22
    volumes:
      - staging-docker:/var/lib/docker
      - staging-user:/home/vpsuser
    env_file:
      - .env