networks:
  main:
    name: ${PROJECT_TAG}.main

services:
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    container_name: ${PROJECT_TAG}.gitlab-ce
    hostname: ${GITLAB_EXTERNAL_URL}
    restart: always
    networks:
      - main
    ports:
      - 80:80
      - 443:443
      - 22:22
    environment:
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_EXTERNAL_URL}'
        gitlab_kas['env']['OWN_PRIVATE_API_URL'] = 'grpcs://${GITLAB_EXTERNAL_URL}:8155'
    volumes:
      - ./gitlab-ce/config:/etc/gitlab
      - ./gitlab-ce/data:/var/opt/gitlab
      - ./gitlab-ce/logs:/var/log/gitlab
    shm_size: 256m

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: ${PROJECT_TAG}.gitlab-runner
    restart: always
    network_mode: host
    environment:
      CACHE_VOLUME: ${PROJECT_TAG}.gitlab-runner-cache
      BUILDS_VOLUME: ${PROJECT_TAG}.gitlab-runner-builds
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - ./gitlab-runner/data:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab-ce
