services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./config:/etc/gitlab-runner
      - ./data:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock