services:
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    hostname: ${GITLAB_CE_HOST}
    restart: always
    ports:
      - ${GITLAB_CE_PORT}:${GITLAB_CE_PORT}
      - ${GITLAB_CE_REGISTRY_PORT}:${GITLAB_CE_REGISTRY_PORT}
    environment:
      GITLAB_ROOT_EMAIL: ${GITLAB_CE_ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${GITLAB_CE_ROOT_PASSWORD}
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_CE_HOST}:${GITLAB_CE_PORT}"
        registry_external_url "http://${GITLAB_CE_HOST}:${GITLAB_CE_REGISTRY_PORT}"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    shm_size: 256m